// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: dron_poc/common.proto

package dron_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1
	Status_STATUS_RUNNING     Status = 2
	Status_STATUS_SUCCESS     Status = 3
	Status_STATUS_FAILURE     Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_RUNNING",
		3: "STATUS_SUCCESS",
		4: "STATUS_FAILURE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_RUNNING":     2,
		"STATUS_SUCCESS":     3,
		"STATUS_FAILURE":     4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_dron_poc_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_dron_poc_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{0}
}

type TaskId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskId) Reset() {
	*x = TaskId{}
	mi := &file_dron_poc_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskId) ProtoMessage() {}

func (x *TaskId) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskId.ProtoReflect.Descriptor instead.
func (*TaskId) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{0}
}

func (x *TaskId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type WorkerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerID) Reset() {
	*x = WorkerID{}
	mi := &file_dron_poc_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerID) ProtoMessage() {}

func (x *WorkerID) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerID.ProtoReflect.Descriptor instead.
func (*WorkerID) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerID) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_dron_poc_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_dron_poc_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_dron_poc_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{4}
}

func (x *TaskOutput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *WorkerID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CurrentTask   *TaskId                `protobuf:"bytes,6,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	IsAlive       bool                   `protobuf:"varint,4,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_dron_poc_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{5}
}

func (x *Worker) GetId() *WorkerID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Worker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Worker) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Worker) GetCurrentTask() *TaskId {
	if x != nil {
		return x.CurrentTask
	}
	return nil
}

func (x *Worker) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Worker) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *TaskId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Command       *Command               `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=dron_poc.Status" json:"status,omitempty"`
	AssignedTo    *TaskId                `protobuf:"bytes,5,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_dron_poc_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetId() *TaskId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Task) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Task) GetAssignedTo() *TaskId {
	if x != nil {
		return x.AssignedTo
	}
	return nil
}

func (x *Task) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// To Coordinator
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_dron_poc_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// From Coordinator
type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *TaskId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_dron_poc_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskResponse) GetId() *TaskId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Worker to Coordinator
type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_dron_poc_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterWorkerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Coordinator to Worker
type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *WorkerID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_dron_poc_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterWorkerResponse) GetId() *WorkerID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Worker to Coordinator
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      *WorkerID              `protobuf:"bytes,1,opt,name=WorkerId,proto3" json:"WorkerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_dron_poc_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskRequest) GetWorkerId() *WorkerID {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

// Coordinator to Worker
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	HasTask       bool                   `protobuf:"varint,2,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_dron_poc_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *GetTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FinishTaskArgs - Arguments when worker reports task completion
type FinishTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *WorkerID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        *TaskId                `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=dron_poc.Status" json:"status,omitempty"`
	Output        *TaskOutput            `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	mi := &file_dron_poc_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{13}
}

func (x *FinishTaskRequest) GetId() *WorkerID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FinishTaskRequest) GetTaskId() *TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *FinishTaskRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *FinishTaskRequest) GetOutput() *TaskOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

type FinishTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskResponse) Reset() {
	*x = FinishTaskResponse{}
	mi := &file_dron_poc_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskResponse) ProtoMessage() {}

func (x *FinishTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dron_poc_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskResponse.ProtoReflect.Descriptor instead.
func (*FinishTaskResponse) Descriptor() ([]byte, []int) {
	return file_dron_poc_common_proto_rawDescGZIP(), []int{14}
}

func (x *FinishTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinishTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dron_poc_common_proto protoreflect.FileDescriptor

const file_dron_poc_common_proto_rawDesc = "" +
	"\n" +
	"\x15dron_poc/common.proto\x12\bdron_poc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n" +
	"\x06TaskId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\" \n" +
	"\bWorkerID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"\x1f\n" +
	"\aCommand\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1f\n" +
	"\aAddress\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"TaskOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x80\x02\n" +
	"\x06Worker\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.dron_poc.WorkerIDR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\aaddress\x18\x03 \x01(\v2\x11.dron_poc.AddressR\aaddress\x123\n" +
	"\fcurrent_task\x18\x06 \x01(\v2\x10.dron_poc.TaskIdR\vcurrentTask\x12\x19\n" +
	"\bis_alive\x18\x04 \x01(\bR\aisAlive\x12A\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"\xff\x02\n" +
	"\x04Task\x12 \n" +
	"\x02id\x18\x01 \x01(\v2\x10.dron_poc.TaskIdR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\acommand\x18\x03 \x01(\v2\x11.dron_poc.CommandR\acommand\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.dron_poc.StatusR\x06status\x121\n" +
	"\vassigned_to\x18\x05 \x01(\v2\x10.dron_poc.TaskIdR\n" +
	"assignedTo\x12=\n" +
	"\fsubmitted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"T\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\acommand\x18\x02 \x01(\v2\x11.dron_poc.CommandR\acommand\"j\n" +
	"\x12CreateTaskResponse\x12 \n" +
	"\x02id\x18\x01 \x01(\v2\x10.dron_poc.TaskIdR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"X\n" +
	"\x15RegisterWorkerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\aaddress\x18\x02 \x01(\v2\x11.dron_poc.AddressR\aaddress\"p\n" +
	"\x16RegisterWorkerResponse\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.dron_poc.WorkerIDR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"@\n" +
	"\x0eGetTaskRequest\x12.\n" +
	"\bWorkerId\x18\x01 \x01(\v2\x12.dron_poc.WorkerIDR\bWorkerId\"j\n" +
	"\x0fGetTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.dron_poc.TaskR\x04task\x12\x19\n" +
	"\bhas_task\x18\x02 \x01(\bR\ahasTask\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xba\x01\n" +
	"\x11FinishTaskRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.dron_poc.WorkerIDR\x02id\x12)\n" +
	"\atask_id\x18\x02 \x01(\v2\x10.dron_poc.TaskIdR\x06taskId\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.dron_poc.StatusR\x06status\x12,\n" +
	"\x06output\x18\x04 \x01(\v2\x14.dron_poc.TaskOutputR\x06output\"H\n" +
	"\x12FinishTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*p\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x03\x12\x12\n" +
	"\x0eSTATUS_FAILURE\x10\x04B\rZ\vdron-proto/b\x06proto3"

var (
	file_dron_poc_common_proto_rawDescOnce sync.Once
	file_dron_poc_common_proto_rawDescData []byte
)

func file_dron_poc_common_proto_rawDescGZIP() []byte {
	file_dron_poc_common_proto_rawDescOnce.Do(func() {
		file_dron_poc_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dron_poc_common_proto_rawDesc), len(file_dron_poc_common_proto_rawDesc)))
	})
	return file_dron_poc_common_proto_rawDescData
}

var file_dron_poc_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dron_poc_common_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dron_poc_common_proto_goTypes = []any{
	(Status)(0),                    // 0: dron_poc.Status
	(*TaskId)(nil),                 // 1: dron_poc.TaskId
	(*WorkerID)(nil),               // 2: dron_poc.WorkerID
	(*Command)(nil),                // 3: dron_poc.Command
	(*Address)(nil),                // 4: dron_poc.Address
	(*TaskOutput)(nil),             // 5: dron_poc.TaskOutput
	(*Worker)(nil),                 // 6: dron_poc.Worker
	(*Task)(nil),                   // 7: dron_poc.Task
	(*CreateTaskRequest)(nil),      // 8: dron_poc.CreateTaskRequest
	(*CreateTaskResponse)(nil),     // 9: dron_poc.CreateTaskResponse
	(*RegisterWorkerRequest)(nil),  // 10: dron_poc.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 11: dron_poc.RegisterWorkerResponse
	(*GetTaskRequest)(nil),         // 12: dron_poc.GetTaskRequest
	(*GetTaskResponse)(nil),        // 13: dron_poc.GetTaskResponse
	(*FinishTaskRequest)(nil),      // 14: dron_poc.FinishTaskRequest
	(*FinishTaskResponse)(nil),     // 15: dron_poc.FinishTaskResponse
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_dron_poc_common_proto_depIdxs = []int32{
	2,  // 0: dron_poc.Worker.id:type_name -> dron_poc.WorkerID
	4,  // 1: dron_poc.Worker.address:type_name -> dron_poc.Address
	1,  // 2: dron_poc.Worker.current_task:type_name -> dron_poc.TaskId
	16, // 3: dron_poc.Worker.last_heartbeat:type_name -> google.protobuf.Timestamp
	1,  // 4: dron_poc.Task.id:type_name -> dron_poc.TaskId
	3,  // 5: dron_poc.Task.command:type_name -> dron_poc.Command
	0,  // 6: dron_poc.Task.status:type_name -> dron_poc.Status
	1,  // 7: dron_poc.Task.assigned_to:type_name -> dron_poc.TaskId
	16, // 8: dron_poc.Task.submitted_at:type_name -> google.protobuf.Timestamp
	16, // 9: dron_poc.Task.started_at:type_name -> google.protobuf.Timestamp
	16, // 10: dron_poc.Task.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 11: dron_poc.CreateTaskRequest.command:type_name -> dron_poc.Command
	1,  // 12: dron_poc.CreateTaskResponse.id:type_name -> dron_poc.TaskId
	4,  // 13: dron_poc.RegisterWorkerRequest.address:type_name -> dron_poc.Address
	2,  // 14: dron_poc.RegisterWorkerResponse.id:type_name -> dron_poc.WorkerID
	2,  // 15: dron_poc.GetTaskRequest.WorkerId:type_name -> dron_poc.WorkerID
	7,  // 16: dron_poc.GetTaskResponse.task:type_name -> dron_poc.Task
	2,  // 17: dron_poc.FinishTaskRequest.id:type_name -> dron_poc.WorkerID
	1,  // 18: dron_poc.FinishTaskRequest.task_id:type_name -> dron_poc.TaskId
	0,  // 19: dron_poc.FinishTaskRequest.status:type_name -> dron_poc.Status
	5,  // 20: dron_poc.FinishTaskRequest.output:type_name -> dron_poc.TaskOutput
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_dron_poc_common_proto_init() }
func file_dron_poc_common_proto_init() {
	if File_dron_poc_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dron_poc_common_proto_rawDesc), len(file_dron_poc_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dron_poc_common_proto_goTypes,
		DependencyIndexes: file_dron_poc_common_proto_depIdxs,
		EnumInfos:         file_dron_poc_common_proto_enumTypes,
		MessageInfos:      file_dron_poc_common_proto_msgTypes,
	}.Build()
	File_dron_poc_common_proto = out.File
	file_dron_poc_common_proto_goTypes = nil
	file_dron_poc_common_proto_depIdxs = nil
}
